CREATE TABLE DPA_REPORT_VERSAMENTO
(
ID_AMM					NUMBER,
VAR_FIXED_RECIPIENTS	VARCHAR2(2000),
CHA_ATTIVA_STRUTTURA	VARCHAR2(1),
CHA_MAIL_STRUTTURA		VARCHAR2(200),
MAIL_SUBJECT			VARCHAR2(100),
MAIL_BODY				VARCHAR2(2000)
)

ALTER TABLE DPA_EL_REGISTRI ADD
(
ID_UTENTE_RESP 			NUMBER
)

ALTER DPA_POLICY_PARER ADD 
(
CHA_ESCLUDI_FATTURE 	VARCHAR2(1)
)