/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// JsonCredentialInfo
    /// </summary>
    [DataContract]
    public partial class JsonCredentialInfo :  IEquatable<JsonCredentialInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonCredentialInfo" /> class.
        /// </summary>
        /// <param name="certs">certs.</param>
        /// <param name="userid">userid.</param>
        /// <param name="status">status.</param>
        public JsonCredentialInfo(List<JsonCertificato> certs = default(List<JsonCertificato>), string userid = default(string), string status = default(string))
        {
            this.Certs = certs;
            this.Userid = userid;
            this.Status = status;
        }
        
        /// <summary>
        /// Gets or Sets Certs
        /// </summary>
        [DataMember(Name="certs", EmitDefaultValue=false)]
        public List<JsonCertificato> Certs { get; set; }

        /// <summary>
        /// Gets or Sets Userid
        /// </summary>
        [DataMember(Name="userid", EmitDefaultValue=false)]
        public string Userid { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonCredentialInfo {\n");
            sb.Append("  Certs: ").Append(Certs).Append("\n");
            sb.Append("  Userid: ").Append(Userid).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonCredentialInfo);
        }

        /// <summary>
        /// Returns true if JsonCredentialInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonCredentialInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonCredentialInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Certs == input.Certs ||
                    this.Certs != null &&
                    this.Certs.SequenceEqual(input.Certs)
                ) && 
                (
                    this.Userid == input.Userid ||
                    (this.Userid != null &&
                    this.Userid.Equals(input.Userid))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Certs != null)
                    hashCode = hashCode * 59 + this.Certs.GetHashCode();
                if (this.Userid != null)
                    hashCode = hashCode * 59 + this.Userid.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
