/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Encryption Algorithm
    /// </summary>
    /// <value>Encryption Algorithm</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JsonEncryptionAlgorithm
    {
        
        /// <summary>
        /// Enum DESEDE3CBC for value: DES_EDE3_CBC
        /// </summary>
        [EnumMember(Value = "DES_EDE3_CBC")]
        DESEDE3CBC = 1,
        
        /// <summary>
        /// Enum RC2CBC for value: RC2_CBC
        /// </summary>
        [EnumMember(Value = "RC2_CBC")]
        RC2CBC = 2,
        
        /// <summary>
        /// Enum IDEACBC for value: IDEA_CBC
        /// </summary>
        [EnumMember(Value = "IDEA_CBC")]
        IDEACBC = 3,
        
        /// <summary>
        /// Enum CAST5CBC for value: CAST5_CBC
        /// </summary>
        [EnumMember(Value = "CAST5_CBC")]
        CAST5CBC = 4,
        
        /// <summary>
        /// Enum AES128CBC for value: AES128_CBC
        /// </summary>
        [EnumMember(Value = "AES128_CBC")]
        AES128CBC = 5,
        
        /// <summary>
        /// Enum AES192CBC for value: AES192_CBC
        /// </summary>
        [EnumMember(Value = "AES192_CBC")]
        AES192CBC = 6,
        
        /// <summary>
        /// Enum AES256CBC for value: AES256_CBC
        /// </summary>
        [EnumMember(Value = "AES256_CBC")]
        AES256CBC = 7,
        
        /// <summary>
        /// Enum CAMELLIA128CBC for value: CAMELLIA128_CBC
        /// </summary>
        [EnumMember(Value = "CAMELLIA128_CBC")]
        CAMELLIA128CBC = 8,
        
        /// <summary>
        /// Enum CAMELLIA192CBC for value: CAMELLIA192_CBC
        /// </summary>
        [EnumMember(Value = "CAMELLIA192_CBC")]
        CAMELLIA192CBC = 9,
        
        /// <summary>
        /// Enum CAMELLIA256CBC for value: CAMELLIA256_CBC
        /// </summary>
        [EnumMember(Value = "CAMELLIA256_CBC")]
        CAMELLIA256CBC = 10
    }

}
