/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Complex object, it provides a Sign Request for a PDF document
    /// </summary>
    [DataContract]
    public partial class JsonBodyRequestPdfSignature :  IEquatable<JsonBodyRequestPdfSignature>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonBodyRequestPdfSignature" /> class.
        /// </summary>
        /// <param name="request">Object that contains a Signature Request.</param>
        /// <param name="apparence">Object that contains the needed parameters for PAdES signature.</param>
        public JsonBodyRequestPdfSignature(JsonSignRequest request = default(JsonSignRequest), JsonPdfSignApparence apparence = default(JsonPdfSignApparence))
        {
            this.Request = request;
            this.Apparence = apparence;
        }
        
        /// <summary>
        /// Object that contains a Signature Request
        /// </summary>
        /// <value>Object that contains a Signature Request</value>
        [DataMember(Name="request", EmitDefaultValue=false)]
        public JsonSignRequest Request { get; set; }

        /// <summary>
        /// Object that contains the needed parameters for PAdES signature
        /// </summary>
        /// <value>Object that contains the needed parameters for PAdES signature</value>
        [DataMember(Name="apparence", EmitDefaultValue=false)]
        public JsonPdfSignApparence Apparence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonBodyRequestPdfSignature {\n");
            sb.Append("  Request: ").Append(Request).Append("\n");
            sb.Append("  Apparence: ").Append(Apparence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonBodyRequestPdfSignature);
        }

        /// <summary>
        /// Returns true if JsonBodyRequestPdfSignature instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonBodyRequestPdfSignature to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonBodyRequestPdfSignature input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Request == input.Request ||
                    (this.Request != null &&
                    this.Request.Equals(input.Request))
                ) && 
                (
                    this.Apparence == input.Apparence ||
                    (this.Apparence != null &&
                    this.Apparence.Equals(input.Apparence))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Request != null)
                    hashCode = hashCode * 59 + this.Request.GetHashCode();
                if (this.Apparence != null)
                    hashCode = hashCode * 59 + this.Apparence.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
