/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Mark Object. Order is important for WSDL.
    /// </summary>
    [DataContract]
    public partial class JsonMark :  IEquatable<JsonMark>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonMark" /> class.
        /// </summary>
        /// <param name="signername">The signer name..</param>
        /// <param name="description">The mark description..</param>
        /// <param name="status">The mark status..</param>
        public JsonMark(string signername = default(string), string description = default(string), string status = default(string))
        {
            this.Signername = signername;
            this.Description = description;
            this.Status = status;
        }
        
        /// <summary>
        /// The signer name.
        /// </summary>
        /// <value>The signer name.</value>
        [DataMember(Name="signername", EmitDefaultValue=false)]
        public string Signername { get; set; }

        /// <summary>
        /// The mark description.
        /// </summary>
        /// <value>The mark description.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The mark status.
        /// </summary>
        /// <value>The mark status.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonMark {\n");
            sb.Append("  Signername: ").Append(Signername).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonMark);
        }

        /// <summary>
        /// Returns true if JsonMark instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonMark to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonMark input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Signername == input.Signername ||
                    (this.Signername != null &&
                    this.Signername.Equals(input.Signername))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Signername != null)
                    hashCode = hashCode * 59 + this.Signername.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
