/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Object contains the result of signature
    /// </summary>
    [DataContract]
    public partial class JsonSignHashReturn :  IEquatable<JsonSignHashReturn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonSignHashReturn" /> class.
        /// </summary>
        /// <param name="cert">Byte Array that contains the certificate (onlu if request).</param>
        /// <param name="certID">ID of certificate used for signature.</param>
        /// <param name="description">Description of generated error and/or details for error code returned.</param>
        /// <param name="returnCode">Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;li&gt;\&quot;0005\&quot; -&gt; Trasportation type not valid&lt;/li&gt;  &lt;li&gt;\&quot;0006\&quot; -&gt; Trasportation type not authorized&lt;/li&gt;  &lt;li&gt;\&quot;0007\&quot; -&gt; Profile of PDF Signature not valid&lt;/li&gt;  &lt;li&gt;\&quot;0008\&quot; -&gt; Impossible to complete time-stamp marking operation&lt;/li&gt;  &lt;li&gt;\&quot;0009\&quot; -&gt; Delegated credential not valid&lt;/li&gt;  &lt;li&gt;\&quot;0010\&quot; -&gt; User status not valid&lt;/li&gt;  &lt;/ul&gt;.</param>
        /// <param name="signature">Byte Array that contains the result of signature.</param>
        /// <param name="status">Result of signature:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;.</param>
        /// <param name="code">For compatibility with new architecture ONLY. DO NOT USE!.</param>
        /// <param name="message">For compatibility with new architecture ONLY. DO NOT USE!.</param>
        public JsonSignHashReturn(string cert = default(string), string certID = default(string), string description = default(string), string returnCode = default(string), string signature = default(string), string status = default(string), string code = default(string), string message = default(string))
        {
            this.Cert = cert;
            this.CertID = certID;
            this.Description = description;
            this.ReturnCode = returnCode;
            this.Signature = signature;
            this.Status = status;
            this.Code = code;
            this.Message = message;
        }
        
        /// <summary>
        /// Byte Array that contains the certificate (onlu if request)
        /// </summary>
        /// <value>Byte Array that contains the certificate (onlu if request)</value>
        [DataMember(Name="cert", EmitDefaultValue=false)]
        public string Cert { get; set; }

        /// <summary>
        /// ID of certificate used for signature
        /// </summary>
        /// <value>ID of certificate used for signature</value>
        [DataMember(Name="certID", EmitDefaultValue=false)]
        public string CertID { get; set; }

        /// <summary>
        /// Description of generated error and/or details for error code returned
        /// </summary>
        /// <value>Description of generated error and/or details for error code returned</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;li&gt;\&quot;0005\&quot; -&gt; Trasportation type not valid&lt;/li&gt;  &lt;li&gt;\&quot;0006\&quot; -&gt; Trasportation type not authorized&lt;/li&gt;  &lt;li&gt;\&quot;0007\&quot; -&gt; Profile of PDF Signature not valid&lt;/li&gt;  &lt;li&gt;\&quot;0008\&quot; -&gt; Impossible to complete time-stamp marking operation&lt;/li&gt;  &lt;li&gt;\&quot;0009\&quot; -&gt; Delegated credential not valid&lt;/li&gt;  &lt;li&gt;\&quot;0010\&quot; -&gt; User status not valid&lt;/li&gt;  &lt;/ul&gt;
        /// </summary>
        /// <value>Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;li&gt;\&quot;0005\&quot; -&gt; Trasportation type not valid&lt;/li&gt;  &lt;li&gt;\&quot;0006\&quot; -&gt; Trasportation type not authorized&lt;/li&gt;  &lt;li&gt;\&quot;0007\&quot; -&gt; Profile of PDF Signature not valid&lt;/li&gt;  &lt;li&gt;\&quot;0008\&quot; -&gt; Impossible to complete time-stamp marking operation&lt;/li&gt;  &lt;li&gt;\&quot;0009\&quot; -&gt; Delegated credential not valid&lt;/li&gt;  &lt;li&gt;\&quot;0010\&quot; -&gt; User status not valid&lt;/li&gt;  &lt;/ul&gt;</value>
        [DataMember(Name="return_code", EmitDefaultValue=false)]
        public string ReturnCode { get; set; }

        /// <summary>
        /// Byte Array that contains the result of signature
        /// </summary>
        /// <value>Byte Array that contains the result of signature</value>
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public string Signature { get; set; }

        /// <summary>
        /// Result of signature:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;
        /// </summary>
        /// <value>Result of signature:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// For compatibility with new architecture ONLY. DO NOT USE!
        /// </summary>
        /// <value>For compatibility with new architecture ONLY. DO NOT USE!</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// For compatibility with new architecture ONLY. DO NOT USE!
        /// </summary>
        /// <value>For compatibility with new architecture ONLY. DO NOT USE!</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonSignHashReturn {\n");
            sb.Append("  Cert: ").Append(Cert).Append("\n");
            sb.Append("  CertID: ").Append(CertID).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ReturnCode: ").Append(ReturnCode).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonSignHashReturn);
        }

        /// <summary>
        /// Returns true if JsonSignHashReturn instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonSignHashReturn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonSignHashReturn input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cert == input.Cert ||
                    (this.Cert != null &&
                    this.Cert.Equals(input.Cert))
                ) && 
                (
                    this.CertID == input.CertID ||
                    (this.CertID != null &&
                    this.CertID.Equals(input.CertID))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ReturnCode == input.ReturnCode ||
                    (this.ReturnCode != null &&
                    this.ReturnCode.Equals(input.ReturnCode))
                ) && 
                (
                    this.Signature == input.Signature ||
                    (this.Signature != null &&
                    this.Signature.Equals(input.Signature))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cert != null)
                    hashCode = hashCode * 59 + this.Cert.GetHashCode();
                if (this.CertID != null)
                    hashCode = hashCode * 59 + this.CertID.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ReturnCode != null)
                    hashCode = hashCode * 59 + this.ReturnCode.GetHashCode();
                if (this.Signature != null)
                    hashCode = hashCode * 59 + this.Signature.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
