/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Object containing the credential to test
    /// </summary>
    [DataContract]
    public partial class JsonBodyRequestTestOtp :  IEquatable<JsonBodyRequestTestOtp>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonBodyRequestTestOtp" /> class.
        /// </summary>
        /// <param name="testCredential">credential to test.</param>
        public JsonBodyRequestTestOtp(JsonTestCredential testCredential = default(JsonTestCredential))
        {
            this.TestCredential = testCredential;
        }
        
        /// <summary>
        /// credential to test
        /// </summary>
        /// <value>credential to test</value>
        [DataMember(Name="test_credential", EmitDefaultValue=false)]
        public JsonTestCredential TestCredential { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonBodyRequestTestOtp {\n");
            sb.Append("  TestCredential: ").Append(TestCredential).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonBodyRequestTestOtp);
        }

        /// <summary>
        /// Returns true if JsonBodyRequestTestOtp instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonBodyRequestTestOtp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonBodyRequestTestOtp input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TestCredential == input.TestCredential ||
                    (this.TestCredential != null &&
                    this.TestCredential.Equals(input.TestCredential))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TestCredential != null)
                    hashCode = hashCode * 59 + this.TestCredential.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
