/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Object containing the credential to test
    /// </summary>
    [DataContract]
    public partial class JsonBodyRequestCredentialsQuery :  IEquatable<JsonBodyRequestCredentialsQuery>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonBodyRequestCredentialsQuery" /> class.
        /// </summary>
        /// <param name="credentialQuery">credential for query.</param>
        public JsonBodyRequestCredentialsQuery(JsonCredentialListQuery credentialQuery = default(JsonCredentialListQuery))
        {
            this.CredentialQuery = credentialQuery;
        }
        
        /// <summary>
        /// credential for query
        /// </summary>
        /// <value>credential for query</value>
        [DataMember(Name="credential_query", EmitDefaultValue=false)]
        public JsonCredentialListQuery CredentialQuery { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonBodyRequestCredentialsQuery {\n");
            sb.Append("  CredentialQuery: ").Append(CredentialQuery).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonBodyRequestCredentialsQuery);
        }

        /// <summary>
        /// Returns true if JsonBodyRequestCredentialsQuery instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonBodyRequestCredentialsQuery to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonBodyRequestCredentialsQuery input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CredentialQuery == input.CredentialQuery ||
                    (this.CredentialQuery != null &&
                    this.CredentialQuery.Equals(input.CredentialQuery))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CredentialQuery != null)
                    hashCode = hashCode * 59 + this.CredentialQuery.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
