/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Document Types
    /// </summary>
    /// <value>Document Types</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JsonDocumentType
    {
        
        /// <summary>
        /// Enum PKCS7 for value: PKCS7
        /// </summary>
        [EnumMember(Value = "PKCS7")]
        PKCS7 = 1,
        
        /// <summary>
        /// Enum PDF for value: PDF
        /// </summary>
        [EnumMember(Value = "PDF")]
        PDF = 2,
        
        /// <summary>
        /// Enum XML for value: XML
        /// </summary>
        [EnumMember(Value = "XML")]
        XML = 3,
        
        /// <summary>
        /// Enum TSD for value: TSD
        /// </summary>
        [EnumMember(Value = "TSD")]
        TSD = 4
    }

}
