/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Complex object that contains a verify result
    /// </summary>
    [DataContract]
    public partial class JsonVerifyReturn :  IEquatable<JsonVerifyReturn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonVerifyReturn" /> class.
        /// </summary>
        /// <param name="binaryoutput">The output in binary form..</param>
        /// <param name="description">The description of the object returned..</param>
        /// <param name="dstPath">The destination path..</param>
        /// <param name="result">The verification results of signatures..</param>
        /// <param name="status">The verification status..</param>
        /// <param name="stream">The stream from which the result can be manipulated..</param>
        public JsonVerifyReturn(string binaryoutput = default(string), string description = default(string), string dstPath = default(string), JsonVerifySignatures result = default(JsonVerifySignatures), string status = default(string), string stream = default(string))
        {
            this.Binaryoutput = binaryoutput;
            this.Description = description;
            this.DstPath = dstPath;
            this.Result = result;
            this.Status = status;
            this.Stream = stream;
        }
        
        /// <summary>
        /// The output in binary form.
        /// </summary>
        /// <value>The output in binary form.</value>
        [DataMember(Name="binaryoutput", EmitDefaultValue=false)]
        public string Binaryoutput { get; set; }

        /// <summary>
        /// The description of the object returned.
        /// </summary>
        /// <value>The description of the object returned.</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// The destination path.
        /// </summary>
        /// <value>The destination path.</value>
        [DataMember(Name="dstPath", EmitDefaultValue=false)]
        public string DstPath { get; set; }

        /// <summary>
        /// The verification results of signatures.
        /// </summary>
        /// <value>The verification results of signatures.</value>
        [DataMember(Name="result", EmitDefaultValue=false)]
        public JsonVerifySignatures Result { get; set; }

        /// <summary>
        /// The verification status.
        /// </summary>
        /// <value>The verification status.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// The stream from which the result can be manipulated.
        /// </summary>
        /// <value>The stream from which the result can be manipulated.</value>
        [DataMember(Name="stream", EmitDefaultValue=false)]
        public string Stream { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonVerifyReturn {\n");
            sb.Append("  Binaryoutput: ").Append(Binaryoutput).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DstPath: ").Append(DstPath).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Stream: ").Append(Stream).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonVerifyReturn);
        }

        /// <summary>
        /// Returns true if JsonVerifyReturn instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonVerifyReturn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonVerifyReturn input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Binaryoutput == input.Binaryoutput ||
                    (this.Binaryoutput != null &&
                    this.Binaryoutput.Equals(input.Binaryoutput))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DstPath == input.DstPath ||
                    (this.DstPath != null &&
                    this.DstPath.Equals(input.DstPath))
                ) && 
                (
                    this.Result == input.Result ||
                    (this.Result != null &&
                    this.Result.Equals(input.Result))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.Stream == input.Stream ||
                    (this.Stream != null &&
                    this.Stream.Equals(input.Stream))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Binaryoutput != null)
                    hashCode = hashCode * 59 + this.Binaryoutput.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.DstPath != null)
                    hashCode = hashCode * 59 + this.DstPath.GetHashCode();
                if (this.Result != null)
                    hashCode = hashCode * 59 + this.Result.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.Stream != null)
                    hashCode = hashCode * 59 + this.Stream.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
