/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Defines json_XMLSignatureType
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JsonXMLSignatureType
    {
        
        /// <summary>
        /// Enum XMLENVELOPED for value: XMLENVELOPED
        /// </summary>
        [EnumMember(Value = "XMLENVELOPED")]
        XMLENVELOPED = 1,
        
        /// <summary>
        /// Enum XMLENVELOPING for value: XMLENVELOPING
        /// </summary>
        [EnumMember(Value = "XMLENVELOPING")]
        XMLENVELOPING = 2,
        
        /// <summary>
        /// Enum XMLDETACHEDINTERNAL for value: XMLDETACHED_INTERNAL
        /// </summary>
        [EnumMember(Value = "XMLDETACHED_INTERNAL")]
        XMLDETACHEDINTERNAL = 3
    }

}
