/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Type of Input (trasport)
    /// </summary>
    /// <value>Type of Input (trasport)</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JsonTypeTransport
    {
        
        /// <summary>
        /// Enum BYNARYNET for value: BYNARYNET
        /// </summary>
        [EnumMember(Value = "BYNARYNET")]
        BYNARYNET = 1,
        
        /// <summary>
        /// Enum FILENAME for value: FILENAME
        /// </summary>
        [EnumMember(Value = "FILENAME")]
        FILENAME = 2,
        
        /// <summary>
        /// Enum DIRECTORYNAME for value: DIRECTORYNAME
        /// </summary>
        [EnumMember(Value = "DIRECTORYNAME")]
        DIRECTORYNAME = 3,
        
        /// <summary>
        /// Enum STREAM for value: STREAM
        /// </summary>
        [EnumMember(Value = "STREAM")]
        STREAM = 4
    }

}
