/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Canonicalized Type
    /// </summary>
    /// <value>Canonicalized Type</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JsonCanonicalizedType
    {
        
        /// <summary>
        /// Enum OMITCOMMENTS for value: ALGO_ID_C14N11_OMIT_COMMENTS
        /// </summary>
        [EnumMember(Value = "ALGO_ID_C14N11_OMIT_COMMENTS")]
        OMITCOMMENTS = 1,
        
        /// <summary>
        /// Enum WITHCOMMENTS for value: ALGO_ID_C14N11_WITH_COMMENTS
        /// </summary>
        [EnumMember(Value = "ALGO_ID_C14N11_WITH_COMMENTS")]
        WITHCOMMENTS = 2
    }

}
