/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Complex object that containing signature credentials for closing a session
    /// </summary>
    [DataContract]
    public partial class JsonBodyRequestCloseSession :  IEquatable<JsonBodyRequestCloseSession>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonBodyRequestCloseSession" /> class.
        /// </summary>
        /// <param name="identity">Object that cointains Signer Credentials for authentication.</param>
        /// <param name="sessionid">Session Id of session that want to close.</param>
        public JsonBodyRequestCloseSession(JsonAuth identity = default(JsonAuth), string sessionid = default(string))
        {
            this.Identity = identity;
            this.Sessionid = sessionid;
        }
        
        /// <summary>
        /// Object that cointains Signer Credentials for authentication
        /// </summary>
        /// <value>Object that cointains Signer Credentials for authentication</value>
        [DataMember(Name="identity", EmitDefaultValue=false)]
        public JsonAuth Identity { get; set; }

        /// <summary>
        /// Session Id of session that want to close
        /// </summary>
        /// <value>Session Id of session that want to close</value>
        [DataMember(Name="sessionid", EmitDefaultValue=false)]
        public string Sessionid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonBodyRequestCloseSession {\n");
            sb.Append("  Identity: ").Append(Identity).Append("\n");
            sb.Append("  Sessionid: ").Append(Sessionid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonBodyRequestCloseSession);
        }

        /// <summary>
        /// Returns true if JsonBodyRequestCloseSession instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonBodyRequestCloseSession to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonBodyRequestCloseSession input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Identity == input.Identity ||
                    (this.Identity != null &&
                    this.Identity.Equals(input.Identity))
                ) && 
                (
                    this.Sessionid == input.Sessionid ||
                    (this.Sessionid != null &&
                    this.Sessionid.Equals(input.Sessionid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Identity != null)
                    hashCode = hashCode * 59 + this.Identity.GetHashCode();
                if (this.Sessionid != null)
                    hashCode = hashCode * 59 + this.Sessionid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
