/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Object containing the User Idendity and the list of Signature Request
    /// </summary>
    [DataContract]
    public partial class JsonBodyRequestPkcs7sSignV2Multiple :  IEquatable<JsonBodyRequestPkcs7sSignV2Multiple>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonBodyRequestPkcs7sSignV2Multiple" /> class.
        /// </summary>
        /// <param name="identity">Object that cointains Signer Credentials for authentication.</param>
        /// <param name="requestList">A list of Signature Request.</param>
        /// <param name="detached">If \&quot;true\&quot; we want detached signatures.</param>
        public JsonBodyRequestPkcs7sSignV2Multiple(JsonAuth identity = default(JsonAuth), List<JsonSignRequestV2> requestList = default(List<JsonSignRequestV2>), bool? detached = default(bool?))
        {
            this.Identity = identity;
            this.RequestList = requestList;
            this.Detached = detached;
        }
        
        /// <summary>
        /// Object that cointains Signer Credentials for authentication
        /// </summary>
        /// <value>Object that cointains Signer Credentials for authentication</value>
        [DataMember(Name="identity", EmitDefaultValue=false)]
        public JsonAuth Identity { get; set; }

        /// <summary>
        /// A list of Signature Request
        /// </summary>
        /// <value>A list of Signature Request</value>
        [DataMember(Name="requestList", EmitDefaultValue=false)]
        public List<JsonSignRequestV2> RequestList { get; set; }

        /// <summary>
        /// If \&quot;true\&quot; we want detached signatures
        /// </summary>
        /// <value>If \&quot;true\&quot; we want detached signatures</value>
        [DataMember(Name="detached", EmitDefaultValue=false)]
        public bool? Detached { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonBodyRequestPkcs7sSignV2Multiple {\n");
            sb.Append("  Identity: ").Append(Identity).Append("\n");
            sb.Append("  RequestList: ").Append(RequestList).Append("\n");
            sb.Append("  Detached: ").Append(Detached).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonBodyRequestPkcs7sSignV2Multiple);
        }

        /// <summary>
        /// Returns true if JsonBodyRequestPkcs7sSignV2Multiple instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonBodyRequestPkcs7sSignV2Multiple to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonBodyRequestPkcs7sSignV2Multiple input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Identity == input.Identity ||
                    (this.Identity != null &&
                    this.Identity.Equals(input.Identity))
                ) && 
                (
                    this.RequestList == input.RequestList ||
                    this.RequestList != null &&
                    this.RequestList.SequenceEqual(input.RequestList)
                ) && 
                (
                    this.Detached == input.Detached ||
                    (this.Detached != null &&
                    this.Detached.Equals(input.Detached))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Identity != null)
                    hashCode = hashCode * 59 + this.Identity.GetHashCode();
                if (this.RequestList != null)
                    hashCode = hashCode * 59 + this.RequestList.GetHashCode();
                if (this.Detached != null)
                    hashCode = hashCode * 59 + this.Detached.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
