/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// An object with the status of verify
    /// </summary>
    [DataContract]
    public partial class JsonArssReturn :  IEquatable<JsonArssReturn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JsonArssReturn" /> class.
        /// </summary>
        /// <param name="description">Description of generated error and/or details for error code returned.</param>
        /// <param name="returnCode">Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;/ul&gt;.</param>
        /// <param name="status">Result:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;.</param>
        public JsonArssReturn(string description = default(string), string returnCode = default(string), string status = default(string))
        {
            this.Description = description;
            this.ReturnCode = returnCode;
            this.Status = status;
        }
        
        /// <summary>
        /// Description of generated error and/or details for error code returned
        /// </summary>
        /// <value>Description of generated error and/or details for error code returned</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;/ul&gt;
        /// </summary>
        /// <value>Enum that indicates error code:  &lt;ul&gt;  &lt;li&gt;\&quot;0001\&quot; -&gt; Generic Error&lt;/li&gt;  &lt;li&gt;\&quot;0002\&quot; -&gt; Incorrect parameters for trasportation type selected&lt;/li&gt;  &lt;li&gt;\&quot;0003\&quot; -&gt; Error after credential check&lt;/li&gt;  &lt;li&gt;\&quot;0004\&quot; -&gt; PIN Error. Details in description field)&lt;/li&gt;  &lt;/ul&gt;</value>
        [DataMember(Name="return_code", EmitDefaultValue=false)]
        public string ReturnCode { get; set; }

        /// <summary>
        /// Result:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;
        /// </summary>
        /// <value>Result:  &lt;ul&gt;  &lt;li&gt;OK&lt;/li&gt;  &lt;li&gt;{errore}: See description and return_code for more details&lt;/li&gt;  &lt;/ul&gt;</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class JsonArssReturn {\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ReturnCode: ").Append(ReturnCode).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JsonArssReturn);
        }

        /// <summary>
        /// Returns true if JsonArssReturn instances are equal
        /// </summary>
        /// <param name="input">Instance of JsonArssReturn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JsonArssReturn input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ReturnCode == input.ReturnCode ||
                    (this.ReturnCode != null &&
                    this.ReturnCode.Equals(input.ReturnCode))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.ReturnCode != null)
                    hashCode = hashCode * 59 + this.ReturnCode.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
