/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Credential Type
    /// </summary>
    /// <value>Credential Type</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum XmlNs0CredentialsType
    {
        
        /// <summary>
        /// Enum SMS for value: SMS
        /// </summary>
        [EnumMember(Value = "SMS")]
        SMS = 1,
        
        /// <summary>
        /// Enum ARUBACALL for value: ARUBACALL
        /// </summary>
        [EnumMember(Value = "ARUBACALL")]
        ARUBACALL = 2,
        
        /// <summary>
        /// Enum CNS2 for value: CNS2
        /// </summary>
        [EnumMember(Value = "CNS2")]
        CNS2 = 3,
        
        /// <summary>
        /// Enum PAPERTOKEN for value: PAPERTOKEN
        /// </summary>
        [EnumMember(Value = "PAPERTOKEN")]
        PAPERTOKEN = 4
    }

}
