/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ArubaSignServiceRest.Client.SwaggerDateConverter;

namespace ArubaSignServiceRest.Model
{
    /// <summary>
    /// Pdf Signature Profile desidered
    /// </summary>
    /// <value>Pdf Signature Profile desidered</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum XmlNs0PDFProfile
    {
        
        /// <summary>
        /// Enum BASIC for value: BASIC
        /// </summary>
        [EnumMember(Value = "BASIC")]
        BASIC = 1,
        
        /// <summary>
        /// Enum PADESBES for value: PADESBES
        /// </summary>
        [EnumMember(Value = "PADESBES")]
        PADESBES = 2,
        
        /// <summary>
        /// Enum PADESLTV for value: PADESLTV
        /// </summary>
        [EnumMember(Value = "PADESLTV")]
        PADESLTV = 3
    }

}
