/* 
 * ArubaSignService
 *
 * <h1>ArubaSignService</h1>
 *
 * OpenAPI spec version: 2.3.2-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ArubaSignServiceRest.Client;
using ArubaSignServiceRest.Model;

namespace ArubaSignServiceRest
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISignServiceApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get server version.
        /// </summary>
        /// <remarks>
        /// Get server version.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string ResourceSignServiceGetVersionGET ();

        /// <summary>
        /// Get server version.
        /// </summary>
        /// <remarks>
        /// Get server version.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ResourceSignServiceGetVersionGETWithHttpInfo ();
        /// <summary>
        /// Do a PDF signature.
        /// </summary>
        /// <remarks>
        /// Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>JsonSignResponse</returns>
        JsonSignResponse ResourceSignServicePdfSignaturePOST (JsonPdfSignRequest body = null);

        /// <summary>
        /// Do a PDF signature.
        /// </summary>
        /// <remarks>
        /// Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>ApiResponse of JsonSignResponse</returns>
        ApiResponse<JsonSignResponse> ResourceSignServicePdfSignaturePOSTWithHttpInfo (JsonPdfSignRequest body = null);
        /// <summary>
        /// Ping server to check if it is up and running.
        /// </summary>
        /// <remarks>
        /// Ping server to check if it is up and running.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        string ResourceSignServicePingGET ();

        /// <summary>
        /// Ping server to check if it is up and running.
        /// </summary>
        /// <remarks>
        /// Ping server to check if it is up and running.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> ResourceSignServicePingGETWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get server version.
        /// </summary>
        /// <remarks>
        /// Get server version.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ResourceSignServiceGetVersionGETAsync ();

        /// <summary>
        /// Get server version.
        /// </summary>
        /// <remarks>
        /// Get server version.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ResourceSignServiceGetVersionGETAsyncWithHttpInfo ();
        /// <summary>
        /// Do a PDF signature.
        /// </summary>
        /// <remarks>
        /// Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>Task of JsonSignResponse</returns>
        System.Threading.Tasks.Task<JsonSignResponse> ResourceSignServicePdfSignaturePOSTAsync (JsonPdfSignRequest body = null);

        /// <summary>
        /// Do a PDF signature.
        /// </summary>
        /// <remarks>
        /// Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>Task of ApiResponse (JsonSignResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<JsonSignResponse>> ResourceSignServicePdfSignaturePOSTAsyncWithHttpInfo (JsonPdfSignRequest body = null);
        /// <summary>
        /// Ping server to check if it is up and running.
        /// </summary>
        /// <remarks>
        /// Ping server to check if it is up and running.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> ResourceSignServicePingGETAsync ();

        /// <summary>
        /// Ping server to check if it is up and running.
        /// </summary>
        /// <remarks>
        /// Ping server to check if it is up and running.
        /// </remarks>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> ResourceSignServicePingGETAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SignServiceApi : ISignServiceApi
    {
        private ArubaSignServiceRest.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SignServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SignServiceApi(String basePath)
        {
            this.Configuration = new ArubaSignServiceRest.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ArubaSignServiceRest.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SignServiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SignServiceApi(ArubaSignServiceRest.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ArubaSignServiceRest.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ArubaSignServiceRest.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ArubaSignServiceRest.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ArubaSignServiceRest.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get server version. Get server version.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string ResourceSignServiceGetVersionGET ()
        {
             ApiResponse<string> localVarResponse = ResourceSignServiceGetVersionGETWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get server version. Get server version.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ResourceSignServiceGetVersionGETWithHttpInfo ()
        {

            var localVarPath = "/SignService/version";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServiceGetVersionGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Get server version. Get server version.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ResourceSignServiceGetVersionGETAsync ()
        {
             ApiResponse<string> localVarResponse = await ResourceSignServiceGetVersionGETAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get server version. Get server version.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ResourceSignServiceGetVersionGETAsyncWithHttpInfo ()
        {

            var localVarPath = "/SignService/version";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServiceGetVersionGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Do a PDF signature. Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>JsonSignResponse</returns>
        public JsonSignResponse ResourceSignServicePdfSignaturePOST (JsonPdfSignRequest body = null)
        {
             ApiResponse<JsonSignResponse> localVarResponse = ResourceSignServicePdfSignaturePOSTWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Do a PDF signature. Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>ApiResponse of JsonSignResponse</returns>
        public ApiResponse< JsonSignResponse > ResourceSignServicePdfSignaturePOSTWithHttpInfo (JsonPdfSignRequest body = null)
        {

            var localVarPath = "/SignService/pdfSignature";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServicePdfSignaturePOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JsonSignResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JsonSignResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(JsonSignResponse)));
        }

        /// <summary>
        /// Do a PDF signature. Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>Task of JsonSignResponse</returns>
        public async System.Threading.Tasks.Task<JsonSignResponse> ResourceSignServicePdfSignaturePOSTAsync (JsonPdfSignRequest body = null)
        {
             ApiResponse<JsonSignResponse> localVarResponse = await ResourceSignServicePdfSignaturePOSTAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Do a PDF signature. Do a PDF signature. Supports multiple signatures in a single transaction.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">The request parameters. (optional)</param>
        /// <returns>Task of ApiResponse (JsonSignResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<JsonSignResponse>> ResourceSignServicePdfSignaturePOSTAsyncWithHttpInfo (JsonPdfSignRequest body = null)
        {

            var localVarPath = "/SignService/pdfSignature";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml", 
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServicePdfSignaturePOST", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<JsonSignResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (JsonSignResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(JsonSignResponse)));
        }

        /// <summary>
        /// Ping server to check if it is up and running. Ping server to check if it is up and running.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>string</returns>
        public string ResourceSignServicePingGET ()
        {
             ApiResponse<string> localVarResponse = ResourceSignServicePingGETWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Ping server to check if it is up and running. Ping server to check if it is up and running.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > ResourceSignServicePingGETWithHttpInfo ()
        {

            var localVarPath = "/SignService/ping";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServicePingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Ping server to check if it is up and running. Ping server to check if it is up and running.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> ResourceSignServicePingGETAsync ()
        {
             ApiResponse<string> localVarResponse = await ResourceSignServicePingGETAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Ping server to check if it is up and running. Ping server to check if it is up and running.
        /// </summary>
        /// <exception cref="ArubaSignServiceRest.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> ResourceSignServicePingGETAsyncWithHttpInfo ()
        {

            var localVarPath = "/SignService/ping";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ResourceSignServicePingGET", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
